import java.sql.*;
import java.util.Set;
import javax.swing.*;
import static javax.swing.UIManager.getString;
import javax.swing.table.DefaultTableModel;

public class Frame1 extends javax.swing.JFrame {

    public Frame1() {
        initComponents();
        tbPatientID.setEnabled(false);
        tbLastName.setEnabled(false);
        tbFirstName.setEnabled(false);
        tbDateOfBirth.setEnabled(false);
        tbGender.setEnabled(false);
        tbMobilePhoneNumber.setEnabled(false);
        tbAddress.setEnabled(false);
        tbCity.setEnabled(false);
        tbState.setEnabled(false);
        tbZipCode.setEnabled(false);
        tbNotes.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbPatientID = new javax.swing.JTextField();
        tbLastName = new javax.swing.JTextField();
        tbFirstName = new javax.swing.JTextField();
        tbDateOfBirth = new javax.swing.JTextField();
        tbGender = new javax.swing.JTextField();
        tbMobilePhoneNumber = new javax.swing.JTextField();
        tbAddress = new javax.swing.JTextField();
        tbCity = new javax.swing.JTextField();
        tbState = new javax.swing.JTextField();
        tbZipCode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNotes = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbPatientID.setAutoscrolls(false);
        tbPatientID.setEnabled(false);
        tbPatientID.setMinimumSize(new java.awt.Dimension(78, 23));
        tbPatientID.setPreferredSize(new java.awt.Dimension(78, 23));

        tbLastName.setMinimumSize(new java.awt.Dimension(78, 23));

        tbFirstName.setMinimumSize(new java.awt.Dimension(78, 23));
        tbFirstName.setSize(new java.awt.Dimension(78, 23));

        tbDateOfBirth.setMinimumSize(new java.awt.Dimension(78, 23));
        tbDateOfBirth.setSize(new java.awt.Dimension(78, 23));

        tbGender.setMinimumSize(new java.awt.Dimension(78, 23));
        tbGender.setSize(new java.awt.Dimension(78, 23));

        tbMobilePhoneNumber.setMinimumSize(new java.awt.Dimension(78, 23));
        tbMobilePhoneNumber.setSize(new java.awt.Dimension(78, 23));

        tbAddress.setMinimumSize(new java.awt.Dimension(78, 23));
        tbAddress.setSize(new java.awt.Dimension(78, 23));

        tbCity.setMinimumSize(new java.awt.Dimension(78, 23));
        tbCity.setSize(new java.awt.Dimension(78, 23));

        tbState.setMinimumSize(new java.awt.Dimension(78, 23));
        tbState.setSize(new java.awt.Dimension(78, 23));

        tbZipCode.setAutoscrolls(false);
        tbZipCode.setMinimumSize(new java.awt.Dimension(78, 23));
        tbZipCode.setSize(new java.awt.Dimension(78, 23));

        tbNotes.setColumns(20);
        tbNotes.setRows(5);
        jScrollPane1.setViewportView(tbNotes);

        jLabel1.setText("PatientID:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("First Name:");

        jLabel4.setText("Date of Birth");

        jLabel5.setText("Mobile Phone");

        jLabel6.setText("Gender");

        jLabel7.setText("Address");

        jLabel8.setText("City");

        jLabel9.setText("State");

        jLabel10.setText("Zip Code");

        jLabel11.setText("Notes");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbPatientID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(tbMobilePhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tbZipCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addComponent(tbCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tbState, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(btnAdd))
                        .addGap(18, 18, 18)
                        .addComponent(btnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tbMobilePhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Unlock text fields
        tbLastName.setEnabled(true);
        tbFirstName.setEnabled(true);
        tbDateOfBirth.setEnabled(true);
        tbGender.setEnabled(true);
        tbMobilePhoneNumber.setEnabled(true);
        tbAddress.setEnabled(true);
        tbCity.setEnabled(true);
        tbState.setEnabled(true);
        tbZipCode.setEnabled(true);
        tbNotes.setEnabled(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // Get input from text fields for variable assignment
        String dbURL = "jdbc:mysql://localhost:3306/medicalhistory?autoReconnct=true";
        String sqlInsert = "INSERT INTO medicalhistory.patient " + 
                "(lastName, firstName, dateOfBirth, gender, mobilePhoneNumber,"
                + "address, city, state, zipCode, notes, deleted) " + "VALUES(?, ?,"
                + "?, ?, ?, ?, ?, ?, ?, ?, ?)";
        
        try
        {
            //Register the driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(dbURL, "root", "P@ssw0rd");
            
            PreparedStatement ps = conn.prepareStatement(sqlInsert);
            ps.setString(1, tbLastName.getText());
            ps.setString(2, tbFirstName.getText());
            ps.setString(3, tbDateOfBirth.getText());
            ps.setString(4, tbGender.getText());
            ps.setString(5, tbMobilePhoneNumber.getText());
            ps.setString(6, tbAddress.getText());
            ps.setString(7, tbCity.getText());
            ps.setString(8, tbState.getText());
            ps.setString(9, tbZipCode.getText());
            ps.setString(10, tbNotes.getText());
            ps.setString(11, "0");
            
            int rowCount = ps.executeUpdate();
            
            if(rowCount > 0)
            {
                System.out.println("Inserted a row!");
                
            }
            else
            {
                System.out.println("Failed to insert a row!");      
            }
            
            // Getting patient count to determine newest PatientID
            String qryStoredProc = "{CALL ReturnPatientCount(?)}";
            CallableStatement getPatientIDCount = conn.prepareCall(qryStoredProc);
            getPatientIDCount.registerOutParameter(1, java.sql.Types.INTEGER); // Registering the OUT parameter correctly
            getPatientIDCount.execute();

            int count = getPatientIDCount.getInt(1);

            // Construct a string representing the patient's information using lastName and firstName from text fields
            String patientInfo = "<html>" +
                     "PatientID: " + count + "<br>" +
                     "Last Name: " + tbLastName.getText() + "<br>" +
                     "First Name: " + tbFirstName.getText() +
                     "</html>";
                                    

            // Add the patient info string to the jList1
            DefaultListModel<String> model = new DefaultListModel<>();
            model.addElement(patientInfo);
            jList1.setModel(model);

            conn.close();
            
        }
        catch (Exception e)
        {
            System.out.println("DB operation failed!" + " " + e);
        }
        
        tbPatientID.setEnabled(false);
        tbLastName.setEnabled(false);
        tbFirstName.setEnabled(false);
        tbDateOfBirth.setEnabled(false);
        tbGender.setEnabled(false);
        tbMobilePhoneNumber.setEnabled(false);
        tbAddress.setEnabled(false);
        tbCity.setEnabled(false);
        tbState.setEnabled(false);
        tbZipCode.setEnabled(false);
        tbNotes.setEnabled(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tbAddress;
    private javax.swing.JTextField tbCity;
    private javax.swing.JTextField tbDateOfBirth;
    private javax.swing.JTextField tbFirstName;
    private javax.swing.JTextField tbGender;
    private javax.swing.JTextField tbLastName;
    private javax.swing.JTextField tbMobilePhoneNumber;
    private javax.swing.JTextArea tbNotes;
    private javax.swing.JTextField tbPatientID;
    private javax.swing.JTextField tbState;
    private javax.swing.JTextField tbZipCode;
    // End of variables declaration//GEN-END:variables
}
